### ISSUE TITLE
Collection actions.create return document

### ISSUE THREAD

**Issue by pspierce** [appwrite/sdk-for-svelte#13]
I hate to bring this here but tried discord several times and likely missed the answer.

I'm executing actions.create(...) on Collection to create a new document and I can't for the life of me figure out how to get that document in <script>...</script>.

I started to write a svelte component to turn around and filter for the doc, but that seemed kinda gross.  I figure there has to be a more direct way?

I am able to get the doc if I iterate over the documents returned from the list with an if-block that looks for a property of the doc that matches a value used to create the doc.  This is kinda ugly and, again, seems unnecessary.

**Comment by TorstenDittmann** [comment]
Hey 👋🏻 

Sorry, Discord can be quite busy 😓 

There are a few ways of doing so. Since the `actions.create` method returns a Promise with the created Document - you can do something like this:

```svelte
<script>
  import { Collection, Document } from "svelte-appwrite";

  let value = "";

  const addTodo = async actions => {
    const newDocument = await actions.create({ label: value }));
    value = "";
  };
</script>

<Collection id="606d59730fe1b" let:actions={actions}>
  <form on:submit|preventDefault={addTodo(actions)}>
    <input type="text" placeholder="add todo" bind:value />
  </form>
</Collection>
```

This is the most verbose form, but anywhere you use the actions.create method - you can get the created document.

This will get easier in the future, when we can properly export actions. That way you can just bind the actions to a variable, but there is a blocker from a library we use. More info: https://github.com/appwrite/sdk-for-svelte/pull/9

**Comment by pspierce** [comment]
Thanks, Torsten.

I'm doing something (or trying to do something) a little different and having trouble wrapping my head around it, still.  I realize this isn't an issue w/ your library but rather my ignorance so I appreciate your help.  I need the instance of the new document in the script and can't seem to resolve the promise:
  
```javascript
<script>
  import { Collection, Document } from "svelte-appwrite";

  let value = "";

  const addTodo = async actions => {
    const newDocument = await actions.create({ label: value }));
    value = "";
  };

let newTodo = addTodo(actions); // No matter what combination of await and/or then I just get a Promise back.

</script>
```

**Comment by TorstenDittmann** [comment]
```svelte
<script>
  import { Collection, Document } from "svelte-appwrite";

  let value = "";
  let newTodo = {};
  const addTodo = async actions => {
    newTodo = await actions.create({ label: value }));
    value = "";
  };

</script>
```

Would something like this work for you?

**Comment by pspierce** [comment]
I'll try again, but I'm kinda already doing that.  In your example, newTodo is always a Promise versus the value I'm intending.

**Comment by pspierce** [comment]
Sad thing is, I had this working at some point but lost some code...

**Comment by pspierce** [comment]
I have tried at least 30 iterations and no matter what I do, I wind up with Promise <pending>

```
              console.log(1);
              instanceName = steps[currentStep].val;
              const resp = actions.create({
                userId: userId,
                instanceName: instanceName,
              });
              instance = resp.then((r) => {
                instance = r;
              });
              console.log("resp", resp);
              console.log("instance: ", instance);
              console.log(4);
```
and I threw this into your Collection.svelte:
```
    create: async (
      data,
      read = [`user:${$currentUser.$id}`],
      write = [`user:${$currentUser.$id}`],
      parentDocument = "",
      parentProperty = "",
      parentPropertyType = "assign"
    ) => {
<! -------------------------  ->
      console.log("3.2");
<! -------------------------  ->

      const response = await Appwrite.sdk.database.createDocument(
        id,
        data,
        read,
        write,
        parentDocument,
        parentProperty,
        parentPropertyType
      );
      actions.reload();
<! -------------------------  ->
      console.log("3.3");
<! -------------------------  ->

      return response;
```
![image](https://user-images.githubusercontent.com/456876/114279458-c4f5fe80-9a02-11eb-9d34-4d2202873d9b.png)

**Comment by TorstenDittmann** [comment]
This is actually exactly what I would expect from the code.

Promises handled with `.then()` are non blocking and that's why `await` is such a nice thing.

For example:

```js
console.log(1);
somePromise().then(n => console.log(2));
console.log(3);
```

This will output 1,3,2 in the console - since the Promise is handled non-blocking. On the other hand, if you do it like this:
```js
console.log(1);
console.log(await somePromise()); // here somePromise will just return a 2
console.log(3);
```

This will output 1,2,3.

So in the best case you should avoid mixing up these 2 approaches to not make the event/lifecycle of the code confusing.

This does actually nothing then in most cases, since the `instance` is very likely not used in that context anymore:
```js
instance = resp.then((r) => {
    instance = r;
});
```


Your example should work like this in an `async` function:

```js
console.log(1);
instanceName = steps[currentStep].val;
const resp = await actions.create({
    userId: userId,
    instanceName: instanceName,
});
console.log("resp", resp);
console.log(4);
```

**Comment by TorstenDittmann** [comment]
<img width="852" alt="Bildschirmfoto 2021-04-10 um 21 37 19" src="https://user-images.githubusercontent.com/1759475/114282565-ef68ab80-9a44-11eb-9d81-ecda750e1b1d.png">

I think we can consider it closed 🎉
