### ISSUE TITLE
Preferences.svelte createEventDispatcher

### ISSUE THREAD

**Issue by pspierce** [appwrite/sdk-for-svelte#14]
Hi.
Preferences.svelte's createEventDispatcher isn't actually called:
const dispatch = createEventDispatcher;
and throws an error, "Function called outside component initialization"
changing to: 
const dispatch = createEventDispatcher();
does the trick.

**Comment by TorstenDittmann** [comment]
Hi,

Sorry for the late answer, I am moving right now and didn't had time or internet to be updated 👍🏻 

Good find, will fix it asap 🙂

**Comment by TorstenDittmann** [comment]
fixed and is about to be released. Thanks!
