### ISSUE TITLE
Not yet published in npm

### ISSUE THREAD

**Issue by peopledrivemecrazy** [appwrite/sdk-for-svelte#2]

**Comment by eldadfux** [comment]
@TorstenDittmann, we already got `appwrite` for the web SDK, `node-appwrite` for the Node.js server SDK, Should I publish as `svelte-appwrite`?

**Comment by TorstenDittmann** [comment]
@eldadfux `svelte-appwrite` fits very well.

I have done 50% of writing proper documentations for this and fixing consistency for naming, callbacks etc. Next weekend I will very likely have a production ready version 👍

**Comment by veighnsche** [comment]
Still haven't found it in npm

**Comment by eldadfux** [comment]
@TorstenDittmann are we good to go with the `npm publish`?

**Comment by TorstenDittmann** [comment]
Yes, just need to finish the docs soon afterwards :+1:

**Comment by TorstenDittmann** [comment]
@eldadfux I just double checked. Functionality is given and works, so could be published. I would like to change the version in package.json first! The documentation will be added little by little.

Edit: version changed ✔️

**Comment by veighnsche** [comment]
@TorstenDittmann @eldadfux  Everything looks good to me. Ready to publish? 👍

**Comment by eldadfux** [comment]
@TorstenDittmann let me know when version is set and I'll publish the package. @Glide7 we should probably add an announcement about this in the community, @TorstenDittmann any chance you could help with it?

**Comment by TorstenDittmann** [comment]
I will leave it on `0.0.1-alpha+001` for now, until the documentation is finished with examples and everything.

Code wise, I don't see anything blocking a release right now 👍 

@Glide7 feel free to contact me if you need informations 🙇

**Comment by eldadfux** [comment]
![image](https://user-images.githubusercontent.com/1297371/100526358-a5d39e80-31d0-11eb-8484-d09c8a843cd4.png)

Done: https://www.npmjs.com/package/svelte-appwrite Awesome work @TorstenDittmann 🎉
