### ISSUE TITLE
🐛 Bug Report: 

### ISSUE THREAD

**Issue by WasimAkhtar** [appwrite/sdk-for-svelte#28]
### 👟 Reproduction steps

If we execute this below svelte code and run in Chrome and Safari browser:

```html
<script>
  import { onMount } from 'svelte'
  import dayjs from 'dayjs'

  export let format = 'YYYY-MM-DD'
	export let date = new Date()
	
  let internal

  const input = (x) => (internal = dayjs(x).format(format))
  const output = (x) => (date = dayjs(x, format).toDate())

  $: input(date)
  $: output(internal)
</script>

<input type="date" bind:value={internal} min="2022-01-01" />
```

### 👍 Expected behavior

The date before "2022-01-01" should not be visible to the user and user can't select the date as well before "2022-01-01".

### 👎 Actual Behavior

It works well in chrome browser but not working in safari browser.
In Safari User can see the date before "2022-01-01" but user can't select the date.

Expected:
Date should not be visible to the user before "2022-01-01" for safari.

### 🎲 Appwrite version

Version 0.10.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@WasimAkhtar, thanks for creating this issue! 🙏🏼 Does this have anything to do with Appwrite?

**Comment by WasimAkhtar** [comment]
Its a platform issue, which svelte date Input not supporting properly in safari browser. but its working fine in chrome browser

**Comment by stnguyen90** [comment]
Closing as this isn't related to Appwrite

**Comment by stnguyen90** [comment]
@WasimAkhtar, perhaps you should create an issue with svelte or the dayjs package.
