### ISSUE TITLE
Cannot find module & Logout not updating

### ISSUE THREAD

**Issue by ksmarty** [appwrite/sdk-for-svelte#3]
Hi there!

I have setup a pretty standard project with login and almost everything works. But, here are my two problems:

1. `"Cannot find module 'svelte-appwrite' or its corresponding type declarations.ts(2307)"` is shown in vscode on each import statement. I am using typescript, which might be the culprit. Everything works as expected, but the error is shown, nonetheless.

2. I used the demo app as a boilerplate and everything but the logout button works. Once pressed it successfully logs out the user (viewable in console), but does not update the webpage. I coped the line `<button on:click={() => actions.logout(actions.reload)}>Logout</button>` yet it does not work.

My one enhancement that would make my particular use case quite helpful would be typescript support/declarations. The community seems to be moving heavily in this directions and I think it be a welcome addition.

If you need more information please let me know.

Thank you!

**Comment by TorstenDittmann** [comment]
TypeScript declarations are a good suggestion, they are definitely on my ToDo now.

About the logout problem, I am investigating it right now :+1:

**Comment by TorstenDittmann** [comment]
@ksmarty Regarding the logout, you have to add following event listener to the `<User />` object `on:successLogout={callback}`.

As you probably noticed the documentation is still a bit sparse, I'm still working on that.

**Comment by ksmarty** [comment]
@TorstenDittmann Thank you for your quick response! However, I'm still a bit lost. What should I set the callback to in order to rerender `<User />`? Thanks!

**Comment by TorstenDittmann** [comment]
You need to use the `actions.reload()` method in the `<User let:actions />` let:directive. Now that you mention it, this approach feels kinda counter intuitive and should be handled automatically. This will also be added to the next release! 👍

**Comment by ksmarty** [comment]
Thank you! My workaround in the meantime is to have a global `actionsObj`. Have the logout button set it to `actions` via `<button on:click={() => {actions.logout((actionsObj = actions));}}>Logout</button>` and have User's `on:successLogout={actionsObj.reload}`.

**Comment by TorstenDittmann** [comment]
@ksmarty https://github.com/appwrite/sdk-for-svelte/pull/4/

TypeScript will arrive soon 😉
